//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblia_курсач.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public books()
        {
            this.issuance_of_books = new HashSet<issuance_of_books>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public int id_publishing { get; set; }
        public int id_publishing_type { get; set; }
        public int id_storage_location { get; set; }
        public byte[] photo { get; set; }
    
        public virtual publication_type publication_type { get; set; }
        public virtual publishingg publishingg { get; set; }
        public virtual storage_location storage_location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issuance_of_books> issuance_of_books { get; set; }
    }
}
