//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblia_курсач.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuance_of_books
    {
        public int id { get; set; }
        public int id_library { get; set; }
        public int id_reader { get; set; }
        public System.DateTime date_of_issue { get; set; }
        public System.DateTime return_date { get; set; }
        public int id_book { get; set; }
    
        public virtual books books { get; set; }
        public virtual librarian librarian { get; set; }
        public virtual reader reader { get; set; }
    }
}
