//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblia_курсач.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliaEntities : DbContext
    {
        public bibliaEntities()
            : base("name=bibliaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<issuance_of_books> issuance_of_books { get; set; }
        public virtual DbSet<librarian> librarian { get; set; }
        public virtual DbSet<publication_type> publication_type { get; set; }
        public virtual DbSet<publishingg> publishingg { get; set; }
        public virtual DbSet<reader> reader { get; set; }
        public virtual DbSet<storage_location> storage_location { get; set; }
    }
}
